GET http://localhost:3000/users



POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "Joana Doe",
    "email": "joana.doe@example.com",
    "password": "securePassword123"
}