// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v7.34.1
// source: libs/common/src/proto/auth.proto

/* eslint-disable */
import type { Metadata } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "authentication";

export interface LoginRequest {
  email: string;
  password: string;
}

export interface RegisterRequest {
  name: string;
  email: string;
  password: string;
  role: string;
}

export interface JwtTokenResponse {
  accessToken: string;
  name: string;
  email: string;
  role: string;
  id: string;
}

export const AUTHENTICATION_PACKAGE_NAME = "authentication";

export interface AuthenticationClient {
  register(request: RegisterRequest, metadata?: Metadata): Observable<JwtTokenResponse>;

  login(request: LoginRequest, metadata?: Metadata): Observable<JwtTokenResponse>;
}

export interface AuthenticationController {
  register(
    request: RegisterRequest,
    metadata?: Metadata,
  ): Promise<JwtTokenResponse> | Observable<JwtTokenResponse> | JwtTokenResponse;

  login(
    request: LoginRequest,
    metadata?: Metadata,
  ): Promise<JwtTokenResponse> | Observable<JwtTokenResponse> | JwtTokenResponse;
}

export function AuthenticationControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["register", "login"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("Authentication", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("Authentication", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const AUTHENTICATION_SERVICE_NAME = "Authentication";
