// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v7.34.1
// source: libs/common/src/proto/dispatch.proto

/* eslint-disable */
import type { Metadata } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "dispatch";

export interface LocalizationRequest {
  id: string;
  lat: number;
  lng: number;
}

export interface LocalizationResponse {
  tripCall: string;
}

export const DISPATCH_PACKAGE_NAME = "dispatch";

export interface DispatchClient {
  locationUpdate(request: Observable<LocalizationRequest>, metadata?: Metadata): Observable<LocalizationResponse>;
}

export interface DispatchController {
  locationUpdate(request: Observable<LocalizationRequest>, metadata?: Metadata): Observable<LocalizationResponse>;
}

export function DispatchControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("Dispatch", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = ["locationUpdate"];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("Dispatch", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const DISPATCH_SERVICE_NAME = "Dispatch";
