// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v7.34.1
// source: libs/common/src/proto/trip.proto

/* eslint-disable */
import type { Metadata } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { wrappers } from "protobufjs";
import { Observable } from "rxjs";
import { Any } from "../../../../google/protobuf/any";
import { Empty } from "../../../../google/protobuf/empty";

export const protobufPackage = "trips";

export interface EstimateRequest {
  origin: string;
  destination: string;
}

export interface EstimateResponse {
  estimatedPrice: number;
  currency: string;
  distance: string;
  duration: string;
  startAddress: string;
  endAddress: string;
}

export interface CreateTripRequest {
  passengerId: string;
  origin: string;
  destination: string;
  durationInSeconds: number;
  distanceInMeters: number;
}

export interface TripResponse {
  id: string;
  passengerId: string;
  driverId?: string | undefined;
  status: string;
  finalPrice?: number | undefined;
  createdAt: Date | undefined;
}

export interface TripListResponse {
  trips: TripResponse[];
}

export interface IdRequest {
  id: string;
}

export const TRIPS_PACKAGE_NAME = "trips";

wrappers[".google.protobuf.Timestamp"] = {
  fromObject(value: Date) {
    return { seconds: value.getTime() / 1000, nanos: (value.getTime() % 1000) * 1e6 };
  },
  toObject(message: { seconds: number; nanos: number }) {
    return new Date(message.seconds * 1000 + message.nanos / 1e6);
  },
} as any;

export interface TripsClient {
  health(request: Empty, metadata?: Metadata): Observable<Any>;

  estimate(request: EstimateRequest, metadata?: Metadata): Observable<EstimateResponse>;

  create(request: CreateTripRequest, metadata?: Metadata): Observable<TripResponse>;

  findOne(request: IdRequest, metadata?: Metadata): Observable<TripResponse>;

  findByUser(request: IdRequest, metadata?: Metadata): Observable<TripListResponse>;
}

export interface TripsController {
  health(request: Empty, metadata?: Metadata): Promise<Any> | Observable<Any> | Any;

  estimate(
    request: EstimateRequest,
    metadata?: Metadata,
  ): Promise<EstimateResponse> | Observable<EstimateResponse> | EstimateResponse;

  create(
    request: CreateTripRequest,
    metadata?: Metadata,
  ): Promise<TripResponse> | Observable<TripResponse> | TripResponse;

  findOne(request: IdRequest, metadata?: Metadata): Promise<TripResponse> | Observable<TripResponse> | TripResponse;

  findByUser(
    request: IdRequest,
    metadata?: Metadata,
  ): Promise<TripListResponse> | Observable<TripListResponse> | TripListResponse;
}

export function TripsControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["health", "estimate", "create", "findOne", "findByUser"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("Trips", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("Trips", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const TRIPS_SERVICE_NAME = "Trips";
