// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v7.34.1
// source: libs/common/src/proto/users.proto

/* eslint-disable */
import type { Metadata } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "identity";

export interface FindOneRequest {
  id: string;
}

export interface UpdateRequest {
  id: string;
  name?: string | undefined;
  email?: string | undefined;
  role?: string | undefined;
  password?: string | undefined;
}

export interface UserResponse {
  id: string;
  name: string;
  email: string;
  role: string;
}

export const IDENTITY_PACKAGE_NAME = "identity";

export interface IdentityServiceClient {
  findOne(request: FindOneRequest, metadata?: Metadata): Observable<UserResponse>;

  update(request: UpdateRequest, metadata?: Metadata): Observable<UserResponse>;
}

export interface IdentityServiceController {
  findOne(
    request: FindOneRequest,
    metadata?: Metadata,
  ): Promise<UserResponse> | Observable<UserResponse> | UserResponse;

  update(request: UpdateRequest, metadata?: Metadata): Promise<UserResponse> | Observable<UserResponse> | UserResponse;
}

export function IdentityServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["findOne", "update"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("IdentityService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("IdentityService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const IDENTITY_SERVICE_NAME = "IdentityService";
