// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v7.34.1
// source: libs/common/src/proto/users.proto

/* eslint-disable */
import type { Metadata } from '@grpc/grpc-js';
import { GrpcMethod, GrpcStreamMethod } from '@nestjs/microservices';
import { Observable } from 'rxjs';

export const protobufPackage = 'identity';

export enum UserRole {
  /** ROLE_UNKNOWN - Obrigatório ser 0 */
  ROLE_UNKNOWN = 0,
  driver = 1,
  rider = 2,
  admin = 3,
  UNRECOGNIZED = -1,
}

export interface FindOneRequest {
  id: string;
}

export interface UpdateRequest {
  id: string;
  name: string;
  role: UserRole;
}

export interface UserResponse {
  id: string;
  name: string;
  /** O campo agora usa o tipo Enum */
  role: UserRole;
}

export const IDENTITY_PACKAGE_NAME = 'identity';

export interface IdentityServiceClient {
  findOne(
    request: FindOneRequest,
    metadata: Metadata,
    ...rest: any
  ): Observable<UserResponse>;

  update(
    request: UpdateRequest,
    metadata: Metadata,
    ...rest: any
  ): Observable<UserResponse>;
}

export interface IdentityServiceController {
  findOne(
    request: FindOneRequest,
    metadata: Metadata,
    ...rest: any
  ): Promise<UserResponse> | Observable<UserResponse> | UserResponse;

  update(
    request: UpdateRequest,
    metadata: Metadata,
    ...rest: any
  ): Promise<UserResponse> | Observable<UserResponse> | UserResponse;
}

export function IdentityServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ['findOne', 'update'];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(
        constructor.prototype,
        method,
      );
      GrpcMethod('IdentityService', method)(
        constructor.prototype[method],
        method,
        descriptor,
      );
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(
        constructor.prototype,
        method,
      );
      GrpcStreamMethod('IdentityService', method)(
        constructor.prototype[method],
        method,
        descriptor,
      );
    }
  };
}

export const IDENTITY_SERVICE_NAME = 'IdentityService';
